version: '3'
services:
  tomcat:
    build: .
    ports:
      - "8080:8080"
  mysql:
    image: "mysql:8.0.2"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: npmanager
    volumes:
       - /mysql-data:/var/lib/mysql
    ports:
       - "3308:3306"
